### ISSUE TITLE
/usr/bin/bash: line 167: gcovr: command not found

### ISSUE THREAD

**Issue by ClausKlein** [aminya/setup-cpp#195]
```bash
installing gcovr from spec 'gcovr==6.0'...
⚠️  Note: '/root/.local/bin' is not on your PATH environment variable. These
    apps will not be globally accessible until your PATH is updated. Run `pipx
    ensurepath` to automatically add it, or manually modify your PATH in your
    shell's config file (i.e. ~/.bashrc).
done! ✨ 🌟 ✨
  installed package gcovr 6.0, installed using Python 3.10.12
  These apps are now globally available
    - gcovr
 ```

see https://gitlab.com/ClausKlein/cmake_template/-/jobs/5032411110#L2349

**Comment by aminya** [comment]
You should `source ~/.cpprc`. It should be added to the PATH automatically.

**Comment by ClausKlein** [comment]
done, but 
```Installing collected packages: packaging, click, argcomplete, userpath, pipx
Successfully installed argcomplete-3.1.1 click-8.1.7 packaging-23.1 pipx-1.2.0 userpath-1.9.0
WARNING: Running pip as the 'root' user can result in broken permissions and conflicting behaviour with the system package manager. It is recommended to use a virtual environment instead: https://pip.pypa.io/warnings/venv
[command]/usr/bin/python3 -c import sys;print(sys.base_exec_prefix);
/usr
"/root/.local/bin" was added to "/root/.cpprc"
/root/.local/bin is already in PATH.
⚠️  All pipx binary directories have been added to PATH. If you are sure you
want to proceed, try again with the '--force' flag.
Otherwise pipx is ready to go! ✨ 🌟 ✨
Installing venv  via pip
ERROR: Could not find a version that satisfies the requirement venv (from versions: none)
ERROR: No matching distribution found for venv
Installing python3-venv  via apt-get
```

**Comment by ClausKlein** [comment]
```yml
.setup_cpp: &setup_cpp |
  curl -LJO "https://github.com/aminya/setup-cpp/releases/download/v0.35.2/setup-cpp-x64-linux"
  chmod +x setup-cpp-x64-linux
  echo -e "section_end:"`date +%s`":.setup_cpp\r\e[0Ksection_start:"`date +%s`":hidden_section\r\e[0K setup cpp"
  export PATH="$HOME/.local/bin:$PATH"
  ./setup-cpp-x64-linux --compiler $compiler --cmake true --ninja true  --ccache true \
    --clangtidy true --clangformat true --cppcheck true --gcovr true
  source ~/.cpprc
  echo -e "section_end:"`date +%s`":hidden_section\r\e[0Ksection_start:"`date +%s`":.setup_cpp\r\e[0K"
  clang-tidy --version
  cmake --version
  ninja --version
  gcc --version
```

**Comment by ClausKlein** [comment]
but the most problems with `v0.35.2` are using github-action:

https://github.com/cpp-best-practices/cmake_template/actions/runs/6102132450
```yml
      - name: Setup Cpp
        uses: aminya/setup-cpp@v1
        with:
          compiler: ${{ matrix.compiler }}
          vcvarsall: ${{ contains(matrix.os, 'windows' )}}

          cmake: true
          ninja: true
          vcpkg: false
          ccache: true
          clangtidy: ${{ env.CLANG_TIDY_VERSION }}


          cppcheck: true

          gcovr: true
          opencppcoverage: true
```
