### ISSUE TITLE
Only install clang-format

### ISSUE THREAD

**Issue by tru** [aminya/setup-cpp#200]
From the github action I do:

```
      - name: Install clang-format
        uses: aminya/setup-cpp@v1
        with:
          compiler: false
          clangformat: 16.0.6
```

But this still installs all of the clang compiler stuff and not just `clang-format-<version>` package. This makes the github action for just code checking much slower.

Can this be fixed?
