### ISSUE TITLE
The setup-cpp action wrongly installs Windows LLVMs to the same folder

### ISSUE THREAD

**Issue by FeignClaims** [aminya/setup-cpp#249]
From the log of [(windows-2022, llvm-16.0.6, *, *) jobs](https://github.com/FeignClaims/cpp_conan_template/actions/runs/9096397009/job/25001719153), for the setup-cpp action specified as

```yaml
- name: Setup cpp
  uses: aminya/setup-cpp@v0.37.0
  with:
    compiler: llvm-16.0.6
    vcvarsall: true

    cmake: true
    ninja: true
    ccache: true
    python: true

    cppcheck: true
    clangtidy: true

    gcovr: 7.2 # The default version 5.2 stucks on macos gcc
    OPENCPPCOVERAGE: TRUE
```

clang-tidy triggers an installation of llvm 17.0.6 (see [Setup cpp#472](https://github.com/FeignClaims/cpp_conan_template/actions/runs/9097935612/job/25006976963?pr=8#step:5:480)). After that, llvm 16.0.6 is triggered to be installed to **the same folder** (see [Setup cpp#554](https://github.com/FeignClaims/cpp_conan_template/actions/runs/9097935612/job/25006976963?pr=8#step:5:564)), which is, however, **not installed according to the log**.

To further ensure that llvm 16.0.6 is not installed, I directly specify the clang version to 16.0.6 in the corresponding [conan profile](https://github.com/FeignClaims/cpp_conan_template/blob/1f3cbd7455127f21fb7d32dea8b7386f78a8955e/conan/profiles/windows-%23-%23-clang-16.0.6-%23#L14), but cmake still uses llvm-17.0.6 according to [Configure cmake#76](https://github.com/FeignClaims/cpp_conan_template/actions/runs/9097935612/job/25006976963?pr=8#step:7:77).

## Upvote & Fund

@aminya is using [Polar.sh](https://polar.sh/aminya) so you can upvote and help fund this issue. The funding is received once the issue is completed & confirmed by you.

Thank you in advance for helping prioritize & fund our backlog!

<br/>

<a href="https://polar.sh/aminya/setup-cpp/issues/249">
<picture>
  <source media="(prefers-color-scheme: dark)" srcset="https://polar.sh/api/github/aminya/setup-cpp/issues/249/pledge.svg?darkmode=1">
  <img alt="Fund with Polar" src="https://polar.sh/api/github/aminya/setup-cpp/issues/249/pledge.svg">
</picture>
</a>
