### ISSUE TITLE
clang-11 through clang-16 fail to install on ubuntu-24.04

### ISSUE THREAD

**Issue by KrystalDelusion** [aminya/setup-cpp#329]
When trying to install clang-11 through clang-16 on ubuntu-24.04 it looks like it's trying to install from source, and as part of that attempts to install libtinfo-dev which is not available in distros newer than jammy (22.04).  For clang<=10 it looks like there it uses libtinfo5 which has a valid fallback.  

Should it be changed to install libtinfo6 for clang>10?  That *is* available on noble (24.04), while [libtinfo-dev on jammy](https://launchpad.net/ubuntu/jammy/+package/libtinfo-dev) says
> This is a transitional package that can safely be removed.

**Comment by aminya** [comment]
Thanks for the report. Do you have logs for this that could speed up the debugging?

**Comment by KrystalDelusion** [comment]
https://github.com/KrystalDelusion/yosys/actions/runs/12857796412 has a step:
```yaml
      - name: Setup Cpp
        uses: aminya/setup-cpp@v1
        with:
          compiler: ${{ matrix.compiler }}
```
Which I ran with clang-10 through clang-19 under ubuntu-latest.

**Comment by aminya** [comment]
Thanks. We can fix this by removing the added LLVM ppa after the failed installation. 
https://github.com/aminya/setup-cpp/blob/1fd813945e55021261b381c59275db442da4082f/src/llvm/llvm.ts#L79

**Comment by aminya** [comment]
I've made a PR that tries to fix this. Can you try it in your repo and see if it is fixed?
```
      - name: Setup Cpp
        uses: aminya/setup-cpp@llvm-remove-repo
        with:
          compiler: ${{ matrix.compiler }}
```
