### ISSUE TITLE
Default to CMake 4

### ISSUE THREAD

**Issue by ClausKlein** [aminya/setup-cpp#420]
The current newest CMake version is 4.0.x and this is needed for import std cxx_modules!

bash-5.2$ cmake --version
cmake version 4.0.3

CMake suite maintained and supported by Kitware (kitware.com/cmake).
bash-5.2$

**Comment by aminya** [comment]
You can pass the version `4.0.3` to use CMake 4 without waiting for the default version to get updated

```
      - name: Setup Cpp
        uses: aminya/setup-cpp@v1
        with:
          cmake: 4.0.3
```

CMake 4 has some breaking changes that apparently removes the support for the projects that have not been updated to support CMake 3.5. That's why I haven't updated to 4 yet. 

https://cmake.org/cmake/help/latest/release/4.0.html#id15
